FROM python:3.11-slim

# Google Chrome ve Driver kurulumu (Selenium için şart)
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    unzip \
    curl \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update && apt-get install -y google-chrome-stable \
    && apt-get clean

# Çalışma dizini
WORKDIR /app
COPY . /app

# Kütüphaneleri kur
RUN pip install --no-cache-dir -r requirements.txt

# Botu çalıştır
CMD ["python", "notbot.py"]
